export { getCoordinates } from './get-coordinates'
export { calculateVotes, getSeats } from './calculate-seats'
export { getSeatAllocations } from './get-seat-allocations'
export { sortSeats } from './sort-seats'
export { styles } from './styles'
